// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_partial_arc_lengths
Eigen::MatrixXd compute_partial_arc_lengths(Eigen::MatrixXd coords);
RcppExport SEXP _PCWprior_compute_partial_arc_lengths(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_partial_arc_lengths(coords));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PCWprior_compute_partial_arc_lengths", (DL_FUNC) &_PCWprior_compute_partial_arc_lengths, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_PCWprior(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
