# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name compute_partial_arc_lengths
#' @title Compute partial arc lengths
#' @description Computes the partial arc lengths from a matrix of coordinates of a SpatialLine
#' @param coords [nx2 matrix] Matrix of the points of the lines
compute_partial_arc_lengths <- function(coords) {
    .Call(`_WCPprior_compute_partial_arc_lengths`, coords)
}

